name = "JuGNLSE"
uuid = "de7fb3a1-4e7f-4e82-aee4-7ca52755e5ed"
authors = ["Brian Sinquin <148503669+brian-sinquin@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
